### ISSUE TITLE
Unable to read beyond the end of the stream problem

### ISSUE THREAD

**Issue by BrunoLiu** [Igor55x/UAAE#19]
I get "Unable to read beyond the end of the stream" error by viewing unpacked LZ4 assets
And here is the error message:
`System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetsTools.NET.AssetsFileReader.ReadInt32()
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField[] baseFields, AssetsFileReader reader, Int64 filePos)
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField baseField, AssetsFileReader reader, Int64 filePos)
   at AssetsAdvancedEditor.Assets.AssetsWorkspace.MakeAssetContainer(AssetItem item, Boolean forceFromCldb) in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Assets\AssetsWorkspace.cs:line 130
   at AssetsAdvancedEditor.Winforms.AssetsViewer.AddAssetItem(AssetsFileInstance fileInst, AssetFileInfoEx info, Int32 fileId) in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 156
   at AssetsAdvancedEditor.Winforms.AssetsViewer.LoadAssetsToList() in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 74
   at AssetsAdvancedEditor.Winforms.AssetsViewer..ctor(AssetsManager am, AssetsFileInstance instance, Boolean fromBundle) in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 63
   at AssetsAdvancedEditor.Winforms.Menu.btnInfo_Click(Object sender, EventArgs e) in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\Menu.cs:line 300
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)`

**Comment by Igor55x** [comment]
Done.
