### ISSUE TITLE
Unhandled Exception : Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by MetricSys** [Igor55x/UAAE#23]
The game I was trying to open up was made in 2020.3.0f1. I've got no clue how to go about fixing this. Appreciate any help. Program also crashed multiple times while trying to copy paste this so it might be a good idea to make a log file or something for troubleshooting down the line.

`System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetsTools.NET.AssetsFileReader.ReadInt32()
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, AssetTypeValueField valueField)
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField[] baseFields, AssetsFileReader reader, Int64 filePos)
   at AssetsTools.NET.AssetTypeInstance..ctor(AssetTypeTemplateField baseField, AssetsFileReader reader, Int64 filePos)
   at AssetsAdvancedEditor.Assets.AssetsWorkspace.MakeAssetContainer(AssetItem item, Boolean forceFromCldb) in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Assets\AssetsWorkspace.cs:line 130
   at AssetsAdvancedEditor.Winforms.AssetsViewer.AddAssetItem(AssetsFileInstance fileInst, AssetFileInfoEx info, Int32 fileId) in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 156
   at AssetsAdvancedEditor.Winforms.AssetsViewer.LoadAssetsToList() in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 83
   at AssetsAdvancedEditor.Winforms.AssetsViewer..ctor(AssetsManager am, AssetsFileInstance instance, Boolean fromBundle) in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 63
   at AssetsAdvancedEditor.Winforms.Menu.openToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Igor55x\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\Menu.cs:line 78
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)`

**Comment by Igor55x** [comment]
Done.
#19
