### ISSUE TITLE
Good day, I ran into a new problem, when I wanted to save a file, I get the following error

### ISSUE THREAD

**Issue by TheCookiss** [Igor55x/UAAE#25]
Good day, I ran into a new problem, when I wanted to save a file, I get the following error:

![Снимок](https://user-images.githubusercontent.com/88102619/127526400-bea22ef6-fbba-4f63-ae3a-a295ceeea7c3.PNG)

I copied for every case what is written there:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsAdvancedEditor.Winforms.AssetsViewer.ClearModified() in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 299
   at AssetsAdvancedEditor.Winforms.AssetsViewer.SaveFiles(Boolean overwrite) in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 437
   at AssetsAdvancedEditor.Winforms.AssetsViewer.AskSaveChanges() in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 409
   at AssetsAdvancedEditor.Winforms.AssetsViewer.AssetsViewer_FormClosing(Object sender, FormClosingEventArgs e) in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 398
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)`

**Please help what to do about it?**

**Comment by TheCookiss** [comment]
And how to fix it?

**Comment by Igor55x** [comment]
> And how to fix it?

An exception is thrown on this line:
`assetList.Items[i].SubItems.Get("Modified").Text = "";`

This happens because the method *`Get(string name)`* returns **null**, although it shouldn't.
So replace the *`Get(string name)`* method with *`[7]`* and that should solve the issue.

**Comment by TheCookiss** [comment]
> 
> 
> > And how to fix it?
> 
> An exception is thrown on this line:
> `assetList.Items[i].SubItems.Get("Modified").Text = "";`
> 
> This happens because the method _`Get(string name)`_ returns **null**, although it shouldn't.
> So replace the _`Get(string name)`_ method with _`[7]`_ and that should solve the issue.

Where to change? How to change

**Comment by TheCookiss** [comment]
Sorry, but how to download it? When downloading, it is not the .exe file that is downloaded from me, but some folder with the program files
