### ISSUE TITLE
An unhandled exception occurred in Export Dump

### ISSUE THREAD

**Issue by mskgroup** [Igor55x/UAAE#28]
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at AssetsAdvancedEditor.Winforms.AssetsViewer.GetSelectedAssetItems() in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 237
   at AssetsAdvancedEditor.Winforms.AssetsViewer.GetSelectedAssets() in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 267
   at AssetsAdvancedEditor.Winforms.AssetsViewer.btnExportDump_Click(Object sender, EventArgs e) in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 563
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by Igor55x** [comment]
Does this happen when you export one or more dumps?

**Comment by mskgroup** [comment]
yes

**Comment by mskgroup** [comment]
It still has the same problem

**Comment by Igor55x** [comment]
The [latest update](https://nightly.link/Igor55x/UAAE/workflows/dotnet-desktop/master/UAAE-Windows.zip) fixes the bug.
