### ISSUE TITLE
Exporting and editing Texture2D: Unable to load DLL 'TexToolWrap.dll' or one of its dependencies

### ISSUE THREAD

**Issue by sdfdger** [Igor55x/UAAE#64]
I'm using the latest build v1.2. I can't export to png and edit textures on any file. [A file with this problem](https://www.file-upload.net/en/download-14868386/globalgamemanagers.assets.html
).

```See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'TexToolWrap.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at Plugins.Texture.PInvoke.DecodeByPVRTexLib(IntPtr data, IntPtr buf, Int32 mode, UInt32 width, UInt32 height)
   at Plugins.Texture.TextureWrapper.DecodePVRTexLib(Byte[] data, Int32 width, Int32 height, TextureFormat format)
   at Plugins.Texture.TextureManager.DecodeTexture(Byte[] data, Int32 width, Int32 height, TextureFormat format)
   at Plugins.Texture.TextureManager.ExportTexture(Byte[] encData, String file, Int32 width, Int32 height, TextureFormat format)
   at Plugins.Texture.Options.ExportTextureOption.SingleExport(IWin32Window owner, AssetsWorkspace workspace, AssetItem selectedItem)
   at Plugins.Texture.Options.ExportTextureOption.ExecutePlugin(IWin32Window owner, AssetsWorkspace workspace, List`1 selectedItems)
   at AssetsAdvancedEditor.Winforms.EditDialog.btnOK_Click(Object sender, EventArgs e) in D:\a\UAAE\UAAE\AssetsAdvancedEditor\Winforms\EditDialog.cs:line 33
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Igor55x** [comment]
Check if the file `TexToolWrap.dll` is in the root program folder.

**Comment by sdfdger** [comment]
TexToolWrap.dll is in the folder

**Comment by Igor55x** [comment]
The export is going well.
Use the latest version of the program, which can be downloaded by clicking on latest build.

**Comment by sdfdger** [comment]
I reinstalled the latest build and nothing changed.

**Comment by sdfdger** [comment]
I installed from that one, and it doesn't work for me.

**Comment by Igor55x** [comment]
> I installed from that one, and it doesn't work for me. These are the Microsoft programs I have installed:
> 
> ```
> Microsoft Visual C++ 2015 Redistributable (x86) - 14.0.24215
> Microsoft Windows Desktop Runtime - 5.0.14 (x64)
> ```

Install these instead of the ones you installed:
https://aka.ms/vs/17/release/vc_redist.x64.exe
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.2-windows-x64-installer
