### ISSUE TITLE
Add asset failed with error. Unity version 2021.1.24f1

### ISSUE THREAD

**Issue by qwerfd2-wustl** [Igor55x/UAAE#66]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetsAdvancedEditor.Assets.AssetsWorkspace.MakeAssetContainer(AssetItem item, Stream ms, Boolean forceFromCldb) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Assets\AssetsWorkspace.cs:line 137
   at AssetsAdvancedEditor.Assets.AssetsWorkspace.AddReplacer(AssetsReplacer replacer, MemoryStream previewStream) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Assets\AssetsWorkspace.cs:line 99
   at AssetsAdvancedEditor.Winforms.AddAssetsDialog.btnOK_Click(Object sender, EventArgs e) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AddAssetsDialog.cs:line 140
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by Igor55x** [comment]
Fixed in 43dd637.
