### ISSUE TITLE
Saving edited file failed, file is corrupted; Unity version 2021.1.24f1

### ISSUE THREAD

**Issue by qwerfd2-wustl** [Igor55x/UAAE#67]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.set_Position(Int64 value)
   at AssetsTools.NET.AssetsFile.Write(AssetsFileWriter writer, Int64 filePos, List`1 replacers, UInt32 fileID, ClassDatabaseFile typeMeta)
   at AssetsAdvancedEditor.Winforms.AssetsViewer.WriteFiles(List`1 replacers, Boolean overwrite) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 453
   at AssetsAdvancedEditor.Winforms.AssetsViewer.SaveFiles(Boolean overwrite) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 433
   at AssetsAdvancedEditor.Winforms.AssetsViewer.saveToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\Lenovo\source\repos\AssetsAdvancedEditor\AssetsAdvancedEditor\Winforms\AssetsViewer.cs:line 693
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by Igor55x** [comment]
Fixed in 43dd637.
